# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNNExample' do
  # Pods for RNNExample
  pod 'GoogleSignIn'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
